### ISSUE TITLE
【本地开发问题】本地开发项目跑起来之后的一些问题

### ISSUE THREAD

**Issue by CherishMvp** [zclzone/isme-nest-serve#5]
- nest服务经常自动断开，特别是在设置后台添加菜单列表的时候，能添加成功。但是成功后再次执行，会经常触发一下错误
![image](https://github.com/zclzone/isme-nest-serve/assets/88085841/f5c7e801-52e4-4c8f-b2a4-5fc39467612e)
 这应该是跟nest服务自动断开连接有关系，我之前项目好像是数据库那块配置然后他会自动断开数据库连接。但是这次的貌似不是数据库问题。希望排查一下

**Comment by zclzone** [comment]
没有复现，你是连的本地的数据库服务还是云服务器的，如果是云服务器那大概就是本地网络或者服务器网络不稳定导致的

**Comment by CherishMvp** [comment]
本地数据库。我同样的环境同样的node版本，在mac下是没问题的。

**Comment by CherishMvp** [comment]
打包后运行看得到错误日志，🚀 启动成功: http://192.168.2.8:4211
node:events:491
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on Commander instance at:
    at RedisSocket.<anonymous> (E:\my_frontend\class_photos\photos-admin\isme-nest-serve\node_modules\.pnpm\@redis+client@1.5.12\node_modules\@redis\client\dist\lib\client\index.js:412:14)
    at RedisSocket.emit (node:events:513:28)
    at RedisSocket._RedisSocket_onSocketError (E:\my_frontend\class_photos\photos-admin\isme-nest-serve\node_modules\.pnpm\@redis+client@1.5.12\node_modules\@redis\client\dist\lib\client\socket.js:218:10)
    at Socket.<anonymous> (E:\my_frontend\class_photos\photos-admin\isme-nest-serve\node_modules\.pnpm\@redis+client@1.5.12\node_modules\@redis\client\dist\lib\client\socket.js:191:127)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
 ELIFECYCLE  Command failed with exit code 1.
排查到应该是redis的问题。重新安装了Windows下的redis5.x版本，显示正常。所有应该是redis兼容问题，之前的是用小皮面板的redis3.x版本。
